### ISSUE TITLE
Add support for Sepolia

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/agreements-app#135]
The UI is missing support for Sepolia:

> ![](https://github.com/nation3/agreements-app/assets/95955389/7fedcff3-f829-40ab-b2a1-30e0440b1f2a)

Sepolia deployments here:  https://github.com/nation3/agreements-contracts/blob/main/packages/contracts/deployments/sepolia.json

**Comment by ravalkenil** [comment]
I can do that, Please assign me

**Comment by brymut** [comment]
Hi @aahna-ashina, could you please have a look at my submission? Also submitted on Dework

- PR : https://github.com/nation3/agreements-app/pull/137

**Comment by TTNguyenDev** [comment]
#147
